// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mo-95tjCjs9ew-JBtCNVO8jFwlZ78hc',
    appId: '1:559731371967:web:56f11e15806716ad183b0a',
    messagingSenderId: '559731371967',
    projectId: 'dashboardflutterflow1',
    authDomain: 'dashboardflutterflow1.firebaseapp.com',
    storageBucket: 'dashboardflutterflow1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9K4opMrKQxQ1aJ02cAUPm5PqhYOEGP8Y',
    appId: '1:559731371967:android:742eb78aa6dcbd28183b0a',
    messagingSenderId: '559731371967',
    projectId: 'dashboardflutterflow1',
    storageBucket: 'dashboardflutterflow1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGSFUcc989Ae8iERbqlwGcbXaxCPTg0eU',
    appId: '1:559731371967:ios:e7df72e3f92cefd8183b0a',
    messagingSenderId: '559731371967',
    projectId: 'dashboardflutterflow1',
    storageBucket: 'dashboardflutterflow1.appspot.com',
    iosBundleId: 'com.example.battlearena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGSFUcc989Ae8iERbqlwGcbXaxCPTg0eU',
    appId: '1:559731371967:ios:e7df72e3f92cefd8183b0a',
    messagingSenderId: '559731371967',
    projectId: 'dashboardflutterflow1',
    storageBucket: 'dashboardflutterflow1.appspot.com',
    iosBundleId: 'com.example.battlearena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1mo-95tjCjs9ew-JBtCNVO8jFwlZ78hc',
    appId: '1:559731371967:web:e18923463058be77183b0a',
    messagingSenderId: '559731371967',
    projectId: 'dashboardflutterflow1',
    authDomain: 'dashboardflutterflow1.firebaseapp.com',
    storageBucket: 'dashboardflutterflow1.appspot.com',
  );
}
